---
linters:
    flake8:
    eslint:
        config: './eslint.config'
    csslint:
        "rules": {
            "order/properties-alphabetical-order": null
        } 

files:
    ignore:
        - 'src/generated/*'
        - 'webroot/bower_components/*'
